#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /usr/bin/picam-frontend
fi
if [ "$1" = "purge" ]; then
    rm -rf /etc/picam-frontend
    rm -rf /usr/share/picam-frontend
fi
